const categories = [
    
        "BEST MOTION PICTURE OF THE YEAR",   
        "BEST PERFORMANCE BY AN ACTOR IN A LEADING ROLE",   
        "BEST PERFORMANCE BY AN ACTRESS IN A LEADING ROLE",   
        "BEST PERFORMANCE BY AN ACTOR IN A SUPPORTING ROLE",   
        "BEST PERFORMANCE BY AN ACTRESS IN A SUPPORTING ROLE",   
        "BEST ACHIEVEMENT IN DIRECTING",   
        "BEST ORIGINAL SCREENPLAY",   
        "BEST ADAPTED SCREENPLAY",   
        "BEST ACHIEVEMENT IN CINEMATOGRAPHY",   
        "BEST ACHIEVEMENT IN FILM EDITING",   
        "BEST ACHIEVEMENT IN PRODUCTION DESIGN",   
        "BEST ACHIEVEMENT IN COSTUME DESIGN",   
        "BEST ACHIEVEMENT IN MAKEUP AND HAIRSTYLING",   
        "BEST ACHIEVEMENT IN MUSIC WRITTEN FOR MOTION PICTURES (ORIGINAL SCORE)",   
        "BEST ACHIEVEMENT IN MUSIC WRITTEN FOR MOTION PICTURES (ORIGINAL SONG)",   
        "BEST ACHIEVEMENT IN SOUND MIXING",   
        "BEST ACHIEVEMENT IN SOUND EDITING",   
        "BEST ACHIEVEMENT IN VISUAL EFFECTS",   
        "BEST DOCUMENTARY FEATURE",   
        "BEST DOCUMENTARY SHORT SUBJECT",   
        "BEST ANIMATED FEATURE FILM",   
        "BEST ANIMATED SHORT FILM",   
        "BEST LIVE ACTION SHORT FILM",   
        "BEST FOREIGN LANGUAGE FILM OF THE YEAR"
];

module.exports = categories;